# Generated by Django 5.0.3 on 2024-03-22 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tamanio', models.CharField(max_length=20)),
                ('id_paquete', models.PositiveBigIntegerField()),
                ('sabor', models.CharField(max_length=30)),
                ('cantidad_disponible', models.PositiveBigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Productos_Gestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
