# Generated by Django 5.0.3 on 2024-03-23 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_pack_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Productos_Gestion',
            new_name='Gestion',
        ),
    ]
