# Generated by Django 5.0.3 on 2024-03-24 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_rename_productos_gestion_gestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='IMAGEN',
            field=models.ImageField(default=1, upload_to='imagenes/'),
            preserve_default=False,
        ),
    ]
