# Generated by Django 5.0.3 on 2024-03-25 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0006_alter_product_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario_Pedido',
            fields=[
                ('ID_USUARIO', models.AutoField(primary_key=True, serialize=False)),
                ('NOMBRES', models.CharField(max_length=50)),
                ('APELLIDOS', models.CharField(max_length=50)),
                ('NUMERO_TELEFONICO', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Detalle_Pedido',
            fields=[
                ('ID_DETALLE', models.AutoField(primary_key=True, serialize=False)),
                ('CANTIDAD', models.PositiveIntegerField()),
                ('ID_PRODUCTO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.product')),
            ],
        ),
        migrations.CreateModel(
            name='Pedidos_TB',
            fields=[
                ('ID_PEDIDO', models.AutoField(primary_key=True, serialize=False)),
                ('ESTADO', models.CharField(max_length=20)),
                ('ID_DETALLE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.detalle_pedido')),
                ('ID_USUARIO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.usuario_pedido')),
            ],
        ),
    ]
