# Generated by Django 5.0.3 on 2024-03-23 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_remove_product_id_product_id_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pack',
            fields=[
                ('ID_PACK', models.AutoField(primary_key=True, serialize=False)),
                ('NOMBRE_PACK', models.CharField(max_length=30)),
                ('CANTIDAD', models.PositiveIntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='product',
            old_name='cantidad_disponible',
            new_name='CANTIDAD_DISPONIBLE',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='nombre',
            new_name='NOMBRE',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='sabor',
            new_name='SABOR',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='tamanio',
            new_name='TAMANIO',
        ),
        migrations.RemoveField(
            model_name='product',
            name='id_paquete',
        ),
        migrations.AddField(
            model_name='product',
            name='ID_PACK',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='productos.pack'),
            preserve_default=False,
        ),
    ]
