# Generated by Django 5.0.3 on 2024-03-25 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_product_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='IMAGEN',
            field=models.ImageField(upload_to='media/image/'),
        ),
    ]
