# Generated by Django 5.0.3 on 2024-03-25 02:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0006_alter_product_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('ID_PROMOCION', models.AutoField(primary_key=True, serialize=False)),
                ('FECHA_PROMOCION', models.DateField()),
                ('FECHA_FIN', models.DateField()),
                ('DESCRIPCION', models.CharField(max_length=100)),
                ('ID_PRODUCTO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.product')),
            ],
        ),
    ]
